package com.paathshala.model;

public enum ErrorType {
    ILLEGAL_ARGUMENTS,
    FILE_UPLOAD_FAILED,
    JSON_PROCESSING_FAILED,
    EXPIRED_JWT_TOKEN,

    DUPLICATE_USERNAME,
    DUPLICATE_EMAIL,
    REGISTRATION_FAILED,
    LOGIN_FAILED,
    UNAUTHORIZED,
    VALIDATION_ERROR,

    CATEGORY_NOT_FOUND,
    DUPLICATE_CATEGORY,
    CATEGORY_NOT_SAVED,
    CATEGORY_NOT_DELETED,
    CATEGORY_NOT_UPDATED,

    COURSE_NOT_FOUND,
    COURSE_NOT_DELETED,
    DUPLICATE_COURSE,
    COURSE_NOT_SAVED,
    COURSE_NOT_UPDATED,

    CONTENT_NOT_FOUND,
    CONTENT_NOT_SAVED,
    CONTENT_NOT_DELETED,
    DUPLICATE_CONTENT,
    CONTENT_NOT_UPDATED,

    PAYMENT_ERROR,
    ENROLLMENT_FAILED,

    DATABASE_ERROR,
    READ_WRITE_FAILED
}
