package com.paathshala.model;

public enum ErrorType {
    ILLEGAL_ARGUMENTS,
    FILE_UPLOAD_FAILED,

    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NOT_SAVED,
    CATEGORY_NOT_DELETED,
    CATEGORY_NOT_UPDATED,

    COURSE_NOT_FOUND,
    COURSE_NOT_DELETED,
    COURSE_ALREADY_EXISTS,
    COURSE_NOT_SAVED,
    COURSE_NOT_UPDATED,

    NOTE_NOT_FOUND,
    NOTE_NOT_SAVED,
    NOTE_NOT_DELETED,
    NOTE_ALREADY_EXISTS,
    NOTE_NOT_UPDATED,

    DATABASE_ERROR,
    USER_NOT_FOUND,
    Authorization_FAILED
}
