package com.paathshala.model;

public enum ErrorType {
    ILLEGAL_ARGUMENTS,
    FILE_UPLOAD_FAILED,
    JSON_PROCESSING_FAILED,
    EXPIRED_JWT_TOKEN,

    DUPLICATE_USERNAME,
    DUPLICATE_EMAIL,
    REGISTRATION_FAILED,
    LOGIN_FAILED,
    UNAUTHORIZED,
    VALIDATION_ERROR,

    CATEGORY_NOT_FOUND,
    DUPLICATE_CATEGORY,
    CATEGORY_NOT_SAVED,
    CATEGORY_NOT_DELETED,
    CATEGORY_NOT_UPDATED,

    COURSE_NOT_FOUND,
    COURSE_NOT_DELETED,
    DUPLICATE_COURSE,
    COURSE_NOT_SAVED,
    COURSE_NOT_UPDATED,

    NOTE_NOT_FOUND,
    NOTE_NOT_SAVED,
    NOTE_NOT_DELETED,
    DUPLICATE_NOTE,
    NOTE_NOT_UPDATED,

    DATABASE_ERROR,
    READ_WRITE_FAILED
}
